### ISSUE TITLE
Please allow bech32 to be larger than 90 characters

### ISSUE THREAD

**Issue by johnta0** [azuchi/bech32rb#2]
I'm writing a gem to decode lightning network invoice which is bech32-encoded string. 

I find it necessary to make the decode method in this gem to allow ```bech.length > 90``` in order to decode LN invoice [defined in BOLT #11](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#requirements)

I think it's most acceptable to allow users to choose max length like [this](https://github.com/bitcoinjs/bech32/blob/master/index.js). 
What do you think about this?

Thanks.

**Comment by azuchi** [comment]
@johnta0 Thank you for pointing out. 
Like bitcoinjs, it changed to be able to specify the maximum data length as an option.

Thanks.
